# Generated by Django 5.0.7 on 2024-07-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='auto_reply_delay',
            field=models.PositiveIntegerField(default=0, help_text='Auto delay for comment in seconds'),
        ),
        migrations.AddField(
            model_name='post',
            name='auto_reply_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
